#!/usr/bin/env python3
"""Generate docs/opcodes.md, the opcode registry the ISA programme arbitrates on.

`add-isa-ergonomic-gates` calls it "the registry and the arbiter", and gate G2
checks every added instruction against it. It is generated rather than
hand-maintained so it cannot drift from the hardware: the implemented set comes
from `rtl/cpu6502_decode.sv`, the cycle counts from the measured table, and the
reservation policy from the constants below.

    make opcodes

Editing this file's RESERVED/EXTENSION tables is how the allocation policy
changes. Editing the generated Markdown is not.
"""

import json
import re
import sys

DECODE = "rtl/cpu6502_decode.sv"
REGISTRY = "tools/65x02/opcodes.txt"
TIMING = "docs/cpu-timing-v2.json"
OUT = "docs/opcodes.md"

# Slots the WDC 65C02 and Rockwell R65C02 define. Never allocated to a new
# instruction: reusing one burns the option of adopting its 65C02 meaning later.
# From add-isa-ergonomic-gates, "Opcode allocation policy".
RESERVED = {}
for _op in range(0x00, 0x100, 0x10):
    RESERVED[_op + 0x07] = "R65C02 RMB/SMB"
    RESERVED[_op + 0x0F] = "R65C02 BBR/BBS"
for _op in (0x04, 0x14): RESERVED[_op] = "65C02 TSB/TRB zp"
for _op in (0x0C, 0x1C): RESERVED[_op] = "65C02 TSB/TRB abs"
for _op in (0x12, 0x32, 0x52, 0x72, 0x92, 0xB2, 0xD2, 0xF2):
    RESERVED[_op] = "65C02 (zp) addressing"
for _op in (0x1A, 0x3A): RESERVED[_op] = "65C02 INC A / DEC A"
for _op in (0x5A, 0x7A): RESERVED[_op] = "65C02 PHY / PLY"
for _op in (0xDA, 0xFA): RESERVED[_op] = "65C02 PHX / PLX"
for _op in (0x64, 0x74, 0x9C, 0x9E): RESERVED[_op] = "65C02 STZ"
RESERVED[0x80] = "65C02 BRA"
RESERVED[0x89] = "65C02 BIT #imm"
RESERVED[0x3C] = "65C02 BIT abs,X"
RESERVED[0x7C] = "65C02 JMP (abs,X)"

# Extension space, assigned per slice.
EXTENSION = {}
for _op in range(0x03, 0x80, 0x10): EXTENSION[_op] = "add-isa-core-ergonomics"
for _op in range(0x83, 0x100, 0x10): EXTENSION[_op] = "add-isa-word-ops"
for _op in range(0x0B, 0x80, 0x10): EXTENSION[_op] = "add-isa-test-and-branch"
for _op in range(0x8B, 0x100, 0x10): EXTENSION[_op] = "add-isa-pointer-ops"
EXTENSION[0x02] = "add-isa-frame-pointer (prefix, opens a second 256-slot page)"


def main():
    rows = {}
    pat = re.compile(r"8'h([0-9A-F]{2}):\s*d\s*=\s*row\(\s*(AM_\w+)[^)]*\);\s*//\s*(.+)$")
    for line in open(DECODE):
        m = pat.search(line.rstrip())
        if m:
            rows[int(m.group(1), 16)] = m.group(3).strip()
    reg = {}
    for line in open(REGISTRY):
        line = line.strip()
        if line and not line.startswith("#"):
            p = line.split()
            reg[int(p[0], 16)] = (p[1], p[2], int(p[3]))
    cyc = json.load(open(TIMING))["opcodes"]

    problems = []
    for op in sorted(set(RESERVED) & set(EXTENSION)):
        problems.append(f"${op:02X} is both reserved ({RESERVED[op]}) and "
                        f"extension space ({EXTENSION[op]})")
    for op in sorted(set(RESERVED) & set(rows)):
        problems.append(f"${op:02X} is implemented but reserved ({RESERVED[op]})")
    if problems:
        for p in problems:
            print("policy conflict: " + p, file=sys.stderr)
        return 1

    claimed = {op: EXTENSION[op] for op in EXTENSION if op in rows}
    unclaimed = {op: EXTENSION[op] for op in EXTENSION if op not in rows}
    free = [op for op in range(256)
            if op not in rows and op not in RESERVED and op not in EXTENSION]

    o = []
    w = o.append
    w("# Opcode registry\n")
    w("**Generated by `tools/65x02/gen_opcodes_md.py` — do not edit by hand.**")
    w("Run `make opcodes` after changing the decode table or the allocation")
    w("policy. The implemented set is read from `rtl/cpu6502_decode.sv`, so this")
    w("file cannot claim an instruction the hardware does not have.\n")
    w("This is the registry gate **G2** of `add-isa-ergonomic-gates` checks")
    w("against: every added instruction is registered here, claims no reserved")
    w("slot, and no slot is claimed twice. A slice that needs a slot edits the")
    w("policy tables in the generator, in the same commit that adds the decode")
    w("row.\n")
    w(f"| | slots |")
    w(f"| --- | --- |")
    w(f"| Implemented | {len(rows)} |")
    w(f"| Reserved for 65C02 compatibility | {len(RESERVED)} |")
    w(f"| Extension space, claimed | {len(claimed)} |")
    w(f"| Extension space, assigned but unclaimed | {len(unclaimed)} |")
    w(f"| Unallocated | {len(free)} |")
    w(f"| **Total** | **{len(rows) + len(RESERVED) + len(unclaimed) + len(free)}** |\n")

    w("## Implemented\n")
    w("Cycles are this core's, measured over the full 65x02 sweep and recorded in")
    w("`docs/cpu-timing-v2.json` — **not** NMOS's. They differ: this core has no")
    w("read-modify-write dummy write, no page-cross penalty and no dummy stack")
    w("access, so pulls, pushes, `RTS`, `RTI`, read-modify-writes and taken")
    w("branches are all cheaper than the 6502 books say. Gate **G4** compares a")
    w("proposed instruction against the sequence it replaces, so it must be")
    w("scored against this column.\n")
    w("| Op | Mnemonic | Mode | Bytes | Cycles | NMOS |")
    w("| --- | --- | --- | --- | --- | --- |")
    for op in sorted(rows):
        if op not in reg:
            w(f"| `${op:02X}` | {rows[op]} | | | | *{claimed[op]}* |")
            continue
        mn, mode, nb = reg[op]
        c = cyc[f"{op:02X}"]
        flag = "" if abs(c["cpi_mean"] - c["nmos_mean"]) < 0.001 else " ◀"
        w(f"| `${op:02X}` | {mn} | {mode} | {nb} | {c['cpi_mean']:.2f}{flag} "
          f"| {c['nmos_mean']:.2f} |")
    w("\n◀ marks an instruction this core executes in fewer cycles than NMOS.\n")

    w("## Reserved — never allocated\n")
    w("Defined by the WDC 65C02 or Rockwell R65C02. Taking one would burn the")
    w("option of adopting its 65C02 meaning later.\n")
    w("| Op | Reserved for |")
    w("| --- | --- |")
    for op in sorted(RESERVED):
        w(f"| `${op:02X}` | {RESERVED[op]} |")

    w("\n## Extension space, assigned but unclaimed\n")
    w("| Op | Assigned to |")
    w("| --- | --- |")
    for op in sorted(unclaimed):
        w(f"| `${op:02X}` | {unclaimed[op]} |")

    w("\n## Unallocated\n")
    if free:
        w("Undefined on NMOS, not defined by the 65C02, and not claimed by any")
        w("slice. Available, but claiming one needs a policy change here first.\n")
        w("```")
        for i in range(0, len(free), 16):
            w("  " + " ".join(f"${op:02X}" for op in free[i:i + 16]))
        w("```")
    else:
        w("None.")

    w("\n## What an unallocated slot does\n")
    w("Every slot with no row in `rtl/cpu6502_decode.sv` decodes to `AM_TRAP`.")
    w("The core latches the opcode and the address it was fetched from, raises a")
    w("sticky `dbg_trap`, and continues as though the byte were a `NOP`. It is")
    w("inert on hardware and named in the simulator: a wild jump or a")
    w("mis-assembled byte becomes a reported failure instead of silent")
    w("corruption. It does not halt — an unrecoverable state is exactly what the")
    w("spec forbids.\n")
    w("A slot stops trapping when a slice claims it, which is one row here and")
    w("one row in the decode table, in the same commit.")

    open(OUT, "w").write("\n".join(o) + "\n")
    print(f"{OUT}: {len(rows)} implemented ({len(claimed)} extension), "
          f"{len(RESERVED)} reserved, {len(unclaimed)} assigned-unclaimed, "
          f"{len(free)} unallocated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
