[package]
name = "verilog-screen-co-simulation"
version = "0.1.0"
authors = ["Hugo Sereno <bytter@gmail.com>"]
publish = false
edition = "2015"

build = "build.rs"

[dependencies]
verilated = { git = "https://github.com/ngildenhuys/verilated-rs", package = "verilated" }
verilated-module = { git = "https://github.com/ngildenhuys/verilated-rs", package = "verilated-module" }
minifb = "0.20.0"

[build-dependencies]
verilator = { git = "https://github.com/ngildenhuys/verilated-rs", package = "verilator", features = ["gen", "module"] }
cc = "1.0"
glob = "0.3.1"
# verilator = "0.1.6"

[profile.release]
debug = false
lto = true
opt-level = 3
