#!/usr/bin/env python3
"""Extract a PICO-8 cart's audio section (.p8.png) as a verbatim RAM image.

The .p8.png ROM already holds music ($3100-$31FF) and SFX ($3200-$42FF) in
the packed runtime format the PSG consumes, so the output is a straight
byte dump plus a report of which sfx()/music() calls appear in the cart's
code (to map game events to slot numbers).

Usage: p8_audio.py cart.p8.png out.asm
"""
import sys
import re
from PIL import Image

MUSIC_BASE, SFX_BASE, AUDIO_END = 0x3100, 0x3200, 0x4300


def rom_from_png(path):
    img = Image.open(path).convert("RGBA")
    data = list(img.getdata())
    rom = bytearray()
    for r, g, b, a in data:
        rom.append(((a & 3) << 6) | ((r & 3) << 4) | ((g & 3) << 2) | (b & 3))
    return rom[:0x8000]


def decompress_code(rom):
    """Old (:c:) and new (pxa) code compression; returns Lua source or ''."""
    code = rom[0x4300:0x8000]
    if code[:4] == b"\x00pxa":
        return pxa_decompress(code)
    if code[:4] == b":c:\x00":
        lut = "\n 0123456789abcdefghijklmnopqrstuvwxyz!#%(){}[]<>+=/*:;.,~_"
        length = (code[4] << 8) | code[5]
        out, i = [], 8
        while i < len(code) - 1 and len(out) < length:
            c = code[i]
            if c == 0:
                out.append(chr(code[i + 1]))
                i += 2
            elif c <= 0x3B:
                out.append(lut[c - 1])
                i += 1
            else:
                off = (c - 0x3C) * 16 + (code[i + 1] & 0xF)
                run = (code[i + 1] >> 4) + 2
                start = len(out) - off
                for k in range(run):
                    out.append(out[start + k])
                i += 2
        return "".join(out)
    return code.split(b"\x00")[0].decode("ascii", "replace")


def pxa_decompress(code):
    """PICO-8 0.2.0+ code compression: LZ77 back-references interleaved with
    move-to-front-coded literals, over an LSB-first bit stream.

    Header (8 bytes): "\\0pxa", then uncompressed and compressed sizes as
    big-endian 16-bit. The compressed size counts the header, which gives a
    free end-to-end check that the bit stream was read correctly.
    """
    unc_size = (code[4] << 8) | code[5]
    com_size = (code[6] << 8) | code[7]
    bits, pos = code[8:], 0

    def bit():
        nonlocal pos
        b = (bits[pos >> 3] >> (pos & 7)) & 1
        pos += 1
        return b

    def read(n):
        v = 0
        for i in range(n):
            v |= bit() << i
        return v

    mtf = list(range(0x100))
    out = bytearray()
    while len(out) < unc_size:
        if bit():
            # Literal, as an index into the move-to-front table. The index is
            # 4 bits wide plus one bit per leading 1, so recently used bytes
            # cost 5 bits and the tail of the table costs more.
            extra = 0
            while bit():
                extra += 1
            idx = read(4 + extra) + (((1 << extra) - 1) << 4)
            ch = mtf[idx]
            out.append(ch)
            del mtf[idx]
            mtf.insert(0, ch)
        else:
            offlen = (5 if bit() else 10) if bit() else 15
            offset = read(offlen) + 1
            if offset == 1 and offlen != 5:
                # Escape: a run of raw bytes, NUL-terminated, bypassing the
                # MTF table. Used for binary string literals, where MTF
                # coding would cost more than the bytes themselves.
                assert offlen == 10, f"unexpected raw-block offlen {offlen}"
                while True:
                    c = read(8)
                    if c == 0:
                        break
                    out.append(c)
            else:
                count = 3
                while True:
                    part = read(3)
                    count += part
                    if part != 7:
                        break
                for _ in range(count):
                    out.append(out[-offset])

    consumed = 8 + (pos + 7) // 8
    if consumed != com_size:
        raise SystemExit(f"pxa: consumed {consumed} bytes, header says "
                         f"{com_size} - decoder is out of step")
    return out.decode("latin-1")


def main():
    cart, out_path = sys.argv[1], sys.argv[2]
    rom = rom_from_png(cart)
    music = rom[MUSIC_BASE:SFX_BASE]
    sfx = rom[SFX_BASE:AUDIO_END]

    used_music = [i for i in range(64) if music[i * 4:i * 4 + 4] != b"\x41\x42\x43\x44"]
    used_sfx = [n for n in range(64) if any(sfx[n * 68 + k] for k in range(64))]
    print(f"music patterns in use: {used_music}")
    print(f"sfx slots with notes:  {used_sfx}")

    src = decompress_code(rom)
    calls = sorted(set(re.findall(r"(?:sfx|music)\s*\(\s*-?\d+[^)]*\)", src)))
    print("audio calls in cart code:")
    for c in calls:
        print("  " + c)

    with open(out_path, "w") as f:
        f.write("; Generated by tools/p8_audio.py from the cart's ROM.\n")
        f.write("; Verbatim PICO-8 audio RAM image: upload to PSG address $3100.\n")
        f.write(f"; Cart audio calls: {' '.join(calls)}\n")
        f.write("audio_data:\n")
        image = music + sfx
        for i in range(0, len(image), 16):
            row = ", ".join(f"${b:02X}" for b in image[i:i + 16])
            f.write(f"    .byte {row}\n")
        f.write(f"AUDIO_BYTES = {len(image)}\n")
    print(f"wrote {out_path}: {len(music) + len(sfx)} bytes")


if __name__ == "__main__":
    main()
