#!/usr/bin/env python3
"""Extract a PICO-8 cart's audio section (.p8.png) as a verbatim RAM image.

The .p8.png ROM already holds music ($3100-$31FF) and SFX ($3200-$42FF) in
the packed runtime format the PSG consumes, so the output is a straight
byte dump plus a report of which sfx()/music() calls appear in the cart's
code (to map game events to slot numbers).

Usage: p8_audio.py cart.p8.png out.asm
"""
import sys
import re
from PIL import Image

MUSIC_BASE, SFX_BASE, AUDIO_END = 0x3100, 0x3200, 0x4300


def rom_from_png(path):
    img = Image.open(path).convert("RGBA")
    data = list(img.getdata())
    rom = bytearray()
    for r, g, b, a in data:
        rom.append(((a & 3) << 6) | ((r & 3) << 4) | ((g & 3) << 2) | (b & 3))
    return rom[:0x8000]


def decompress_code(rom):
    """Old (:c:) and new (pxa) code compression; returns Lua source or ''."""
    code = rom[0x4300:0x8000]
    if code[:4] == b"\x00pxa":
        return pxa_decompress(code)
    if code[:4] == b":c:\x00":
        lut = "\n 0123456789abcdefghijklmnopqrstuvwxyz!#%(){}[]<>+=/*:;.,~_"
        length = (code[4] << 8) | code[5]
        out, i = [], 8
        while i < len(code) - 1 and len(out) < length:
            c = code[i]
            if c == 0:
                out.append(chr(code[i + 1]))
                i += 2
            elif c <= 0x3B:
                out.append(lut[c - 1])
                i += 1
            else:
                off = (c - 0x3C) * 16 + (code[i + 1] & 0xF)
                run = (code[i + 1] >> 4) + 2
                start = len(out) - off
                for k in range(run):
                    out.append(out[start + k])
                i += 2
        return "".join(out)
    return code.split(b"\x00")[0].decode("ascii", "replace")


def pxa_decompress(code):
    raise SystemExit("pxa-compressed cart: extend pxa_decompress "
                     "(only the audio dump works for new-format carts)")


def main():
    cart, out_path = sys.argv[1], sys.argv[2]
    rom = rom_from_png(cart)
    music = rom[MUSIC_BASE:SFX_BASE]
    sfx = rom[SFX_BASE:AUDIO_END]

    used_music = [i for i in range(64) if music[i * 4:i * 4 + 4] != b"\x41\x42\x43\x44"]
    used_sfx = [n for n in range(64) if any(sfx[n * 68 + k] for k in range(64))]
    print(f"music patterns in use: {used_music}")
    print(f"sfx slots with notes:  {used_sfx}")

    src = decompress_code(rom)
    calls = sorted(set(re.findall(r"(?:sfx|music)\s*\(\s*-?\d+[^)]*\)", src)))
    print("audio calls in cart code:")
    for c in calls:
        print("  " + c)

    with open(out_path, "w") as f:
        f.write("; Generated by tools/p8_audio.py from the cart's ROM.\n")
        f.write("; Verbatim PICO-8 audio RAM image: upload to PSG address $3100.\n")
        f.write(f"; Cart audio calls: {' '.join(calls)}\n")
        f.write("audio_data:\n")
        image = music + sfx
        for i in range(0, len(image), 16):
            row = ", ".join(f"${b:02X}" for b in image[i:i + 16])
            f.write(f"    .byte {row}\n")
        f.write(f"AUDIO_BYTES = {len(image)}\n")
    print(f"wrote {out_path}: {len(music) + len(sfx)} bytes")


if __name__ == "__main__":
    main()
