#!/usr/bin/env python3
"""Extract NEMO - Puzzle Pack II's puzzle table from its .p8.png cart.

The cart stores 50 puzzles in a single `pz_str` blob as slash-separated
records of `width,height,encoded,difficulty,name`. `encoded` is the solution
bitmap at 7 bits per character against a 128-entry alphabet (`encode_str`),
row-major, one bit per cell.

This emits the same bitmaps as byte-aligned rows - one byte per 8 cells,
each row starting on a byte boundary - because a 6502 walking a row wants a
whole number of bytes per row far more than it wants the last 4 bits of the
cart's packing. Grid widths are 7..15, so every row is exactly 2 bytes.

Usage: p8_nemo.py cart.p8.png out.asm
"""
import re
import sys

from p8_audio import rom_from_png, decompress_code

ROW_BYTES = 2          # widths are 7..15, so two bytes covers every row
MAX_DIM = 15


def find_encode_str(src):
    """The 128-character alphabet that 7-bit groups index into."""
    m = re.search(r'encode_str\s*=\s*"((?:[^"\\]|\\.)*)"', src)
    if not m:
        raise SystemExit("encode_str not found - cart layout changed")
    return m.group(1).encode("latin-1").decode("unicode_escape")


def decode_bits(encoded, alphabet):
    """Cart encoding: each character contributes 7 bits, MSB first."""
    bits = []
    for ch in encoded:
        idx = alphabet.find(ch)
        if idx < 0:
            raise SystemExit(f"character {ch!r} (0x{ord(ch):02x}) not in alphabet")
        for shift in range(6, -1, -1):
            bits.append((idx >> shift) & 1)
    return bits


def parse_puzzles(src):
    m = re.search(r"pz_str=\[\[\n(.*?)\n\]\]", src, re.S)
    if not m:
        raise SystemExit("pz_str blob not found - cart layout changed")
    alphabet = find_encode_str(src)
    out = []
    for rec in m.group(1).split("/"):
        rec = rec.strip()
        if not rec:
            continue
        f = rec.split(",")
        if len(f) < 3:
            continue
        w, h, enc = int(f[0]), int(f[1]), f[2]
        diff = int(f[3]) if len(f) > 3 and f[3].isdigit() else 0
        name = f[4] if len(f) > 4 else f"puzzle{len(out) + 1}"
        bits = decode_bits(enc, alphabet)
        if len(bits) < w * h:
            raise SystemExit(f"{name}: {len(bits)} bits for a {w}x{h} grid")
        out.append({"w": w, "h": h, "diff": diff, "name": name,
                    "cells": bits[:w * h]})
    return out


def pack_rows(p):
    """Row-major, one byte per 8 cells, each row byte-aligned.

    Bit 7 of the first byte is column 0, matching how the overlay layer and
    the 6502's shift-left-into-carry both want to walk a row.
    """
    rows = []
    for y in range(p["h"]):
        row = bytearray(ROW_BYTES)
        for x in range(p["w"]):
            if p["cells"][y * p["w"] + x]:
                row[x >> 3] |= 0x80 >> (x & 7)
        rows.append(bytes(row))
    return rows


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    cart, out_path = sys.argv[1], sys.argv[2]
    src = decompress_code(rom_from_png(cart))
    puzzles = parse_puzzles(src)

    ver = re.search(r'ver\s*=\s*"([^"]*)"', src)
    widths = sorted({p["w"] for p in puzzles})
    stride_bytes = len(puzzles) * MAX_DIM * ROW_BYTES

    with open(out_path, "w") as f:
        f.write("; Generated by tools/p8_nemo.py - do not edit.\n")
        f.write(f"; Source: NEMO - Puzzle Pack II (mooon), cart ver "
                f"{ver.group(1) if ver else '?'}\n")
        f.write("; Puzzle designs (c) mooon; see docs/corpora.md for attribution.\n")
        f.write(f"; {len(puzzles)} puzzles. Solution bitmaps, row-major, "
                f"{ROW_BYTES} bytes per row, bit 7 = column 0.\n")
        f.write(f"; Grid widths present: {widths} - none is a power of two, so a\n")
        f.write(";   row stride of y*w cannot be reached by shifting. Rows are\n")
        f.write(f";   padded to {ROW_BYTES} bytes here so the BITMAP walk is\n")
        f.write(";   shiftable; the CELL array the game plays on is still y*w.\n")
        f.write(f"NEMO_COUNT = {len(puzzles)}\n")
        f.write(f"NEMO_ROW_BYTES = {ROW_BYTES}\n")
        f.write(f"NEMO_MAX_DIM = {MAX_DIM}\n\n")

        f.write("; Per-puzzle width, height and difficulty, indexed by puzzle number.\n")
        for field, key in (("nemo_w", "w"), ("nemo_h", "h"), ("nemo_diff", "diff")):
            f.write(f"{field}:\n")
            for i in range(0, len(puzzles), 16):
                row = ", ".join(str(p[key]) for p in puzzles[i:i + 16])
                f.write(f"    .byte {row}\n")
        f.write("\n")

        f.write(f"; Solution bitmaps: {MAX_DIM} rows x {ROW_BYTES} bytes per puzzle,\n")
        f.write(f"; so puzzle n starts at nemo_bitmaps + n*{MAX_DIM * ROW_BYTES}.\n")
        f.write("nemo_bitmaps:\n")
        for n, p in enumerate(puzzles):
            f.write(f"    ; {n}: {p['name']} ({p['w']}x{p['h']}, "
                    f"difficulty {p['diff']})\n")
            rows = pack_rows(p)
            for y in range(MAX_DIM):
                row = rows[y] if y < len(rows) else bytes(ROW_BYTES)
                bits = "".join("#" if row[x >> 3] & (0x80 >> (x & 7)) else "."
                               for x in range(p["w"]))
                data = ", ".join(f"${b:02X}" for b in row)
                f.write(f"    .byte {data}    ; {bits}\n")
        f.write(f"NEMO_BITMAP_BYTES = {stride_bytes}\n")

    filled = sum(sum(p["cells"]) for p in puzzles)
    cells = sum(p["w"] * p["h"] for p in puzzles)
    print(f"wrote {out_path}")
    print(f"  {len(puzzles)} puzzles, {cells} cells ({filled} filled), "
          f"{stride_bytes} bytes of bitmap")
    print(f"  widths {widths}, heights {sorted({p['h'] for p in puzzles})}")
    print(f"  powers of two among widths: "
          f"{[w for w in widths if w and not (w & (w - 1))] or 'none'}")


if __name__ == "__main__":
    main()
