#!/usr/bin/env python3
"""Derive the MINIMAL exact buffer geometry for the adopted PSG.

`psg_hw_forms.py` priced the arithmetic; this prices the storage. The
adopted reverb comb is the only stage that needs a RAM rather than
registers, and a literal transcription of the binary's structure (eight
183-sample slots per voice, sized by the comb's 17-bit feedback fixpoint)
does not fit the iCE40's 15-EBR ceiling. Every claim below is either

  PROVED    - byte-equality over the whole deterministic oracle matrix, or
              exhaustive equality over a stated domain, or an arithmetic
              identity checked over its full reachable range
  MEASURED  - an observation about the corpus, evidence and not a bound
  note      - a derivation from the recorded reverse engineering

so a geometry that comes out PROVED can be built with no fidelity risk.
The reference model is tools/psg_binary_model.py (byte-exact against the
adopt-exact PICO-8 exports); this tool drives it through `make_history`,
so the geometry study and the reference path share one implementation of
the ring. Six of the matrix's cases exist because of this study: the
fixpoint ladder, the onset, level and pair probes generated by
psg_oracle.py and captured from PICO-8 on 2026-07-28 (task 5.1a).

Sections:
  layout - what the binary allocates per voice, and which of it a replica
           must actually keep; the entry width the layout implies
  entry  - the entry width, pinned from both sides by the captured
           fixpoint ladder; the comb's narrower accumulator form
  depth  - the ring as a flat sample buffer: 732 entries, not 1,464, and
           which slots of the binary's eight are never read
  count  - how many rings a replica needs, from the concurrently
           advancing playback states
  corpus - what the shipped carts actually ask for
  levers - what else can be freed, and what each one unlocks
  borrow - storage strategies from other sound chips (Paula, S-DSP,
           OPN-style rotating state), priced for THIS fabric
  fit    - block cost per target against the measured EBR census, and the
           verdict per build
  synth  - the block-cost claims re-measured through yosys (slow)

Usage: psg_buffers.py [section ...] [--cases DIR] [--reference DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import psg_binary_model as M

FAILURES: list[str] = []
CASES = Path("build/psg_oracle/cases")
REFS = Path("build/psg_oracle/adopt-exact/reference")
SCRATCH = Path("build/psg_buffers")   # synthesis probes only

TICK = M.TICK_SAMPLES                       # 183 samples per tick
BLEND = M.BLEND_SAMPLES                     # 64-sample crossfade
LOOKBACK = {1: 2 * TICK, 2: 4 * TICK}       # 366 / 732 samples

# iCE40 EBR: one 4 Kbit block, four legal aspect ratios. Gowin GW2AR-18C
# BSRAM: 18 Kbit. Two cost models per target: the ASPECT figure (blocks
# needed if one ratio has to cover depth x width) and the FLOOR
# (ceil(bits/capacity)). Yosys reaches the floor rather than the aspect
# figure - `memory_libmap` packs several narrow entries into one wide word
# and lane-selects with the high address bits, paying LUT4s for the mux.
# The in-tree witness is the shipping 732 x 10-bit revbuf: 7,320 bits in
# TWO blocks, which no single aspect ratio can do. The `synth` section
# measures the floor claim per candidate geometry.
ICE40 = ("iCE40 EBR", 4096, [(256, 16), (512, 8), (1024, 4), (2048, 2)])
GOWIN = ("Gowin BSRAM", 18432, [(512, 36), (1024, 18), (2048, 9),
                                (4096, 4), (8192, 2), (16384, 1)])


def report(name: str, ok: bool, detail: str) -> None:
    tag = "PROVED " if ok else "REFUTED"
    print(f"  {tag} {name:32s} {detail}")
    if not ok:
        FAILURES.append(name)


def measured(name: str, detail: str) -> None:
    print(f"  MEASURED {name:32s} {detail}")


def note(detail: str) -> None:
    print(f"  note     {detail}")


def blocks(depth: int, width: int, target) -> int:
    """Block cost: the bit floor, which is what yosys achieves."""
    return -(-depth * width // target[1])


def aspect(depth: int, width: int, target) -> tuple[int, tuple[int, int]]:
    """Blocks under one aspect ratio, and the winning ratio."""
    best = None
    for d, w in target[2]:
        n = -(-depth // d) * -(-width // w)
        if best is None or n < best[0]:
            best = (n, (d, w))
    return best


# --- ring geometries under test ---------------------------------------------

def clamp_store(bits: int | None, mode: str):
    """The storage element: what a `bits`-wide RAM cell gives back."""
    if bits is None:
        return lambda v: v
    lo, hi = -(1 << (bits - 1)), (1 << (bits - 1)) - 1
    if mode == "sat":
        return lambda v: lo if v < lo else hi if v > hi else v
    span = 1 << bits
    return lambda v: ((v - lo) % span) + lo          # two's-complement wrap


class Ring(M.SlotRing):
    """The binary's eight-slot ring with a storage width, and the choice
    of whether that width is also the voice's sample-buffer width. The
    binary's two buffers are both int16 and the wrap is observable in the
    mixed output, so `ring_only=False` at 16 bits IS the reference cell;
    `ring_only=True` isolates the RAM from the voice's sample register,
    and `bits=None` is the unbounded arithmetic the cell replaces."""

    def __init__(self, bits=16, mode="wrap", ring_only=False):
        super().__init__()
        self.cell = clamp_store(bits, mode)
        self.ring_only = ring_only

    def push(self, samples):
        out = [self.cell(v) for v in samples]
        for v in out:
            M.probe("ring.entry", v)
        self.slots[self.rpos] = out
        self.rpos = (self.rpos + 1) & 7
        return samples if self.ring_only else out


class FlatRing(Ring):
    """One flat circular sample buffer per voice instead of eight
    tick-quantized slots: the candidate the depth section proves."""

    def __init__(self, depth, bits=16, mode="wrap", ring_only=False):
        super().__init__(bits, mode, ring_only)
        self.buf = [0] * depth
        self.n = 0

    def tap(self, level):
        d, base = len(self.buf), self.n - LOOKBACK[level]
        return [self.buf[(base + i) % d] for i in range(TICK)]

    def push(self, samples):
        out = [self.cell(v) for v in samples]
        for v in out:
            M.probe("ring.entry", v)
        d = len(self.buf)
        for i, v in enumerate(out):
            self.buf[(self.n + i) % d] = v
        self.n += TICK
        return samples if self.ring_only else out


class LazyRing(Ring):
    """Writes only while the comb is enabled - the geometry a shared ring
    POOL would have (a voice with reverb off owns no storage)."""

    def __init__(self):
        super().__init__()
        self.armed = False

    def tap(self, level):
        self.armed = True
        return super().tap(level)

    def push(self, samples):
        # The voice's sample buffer is int16 either way; what a pool drops
        # is the STORE, not the truncation.
        out = [self.cell(v) for v in samples]
        if self.armed:
            self.armed = False
            self.slots[self.rpos] = out
            self.rpos = (self.rpos + 1) & 7
        return out


# --- the oracle matrix, driven under a geometry ------------------------------

_matrix: list[dict] | None = None
_refs: dict[str, list[int]] = {}


def matrix() -> list[dict]:
    global _matrix
    if _matrix is None:
        cases = json.loads((CASES / "manifest.json").read_text())["cases"]
        _matrix = [c for c in cases
                   if not c["long"] and not c["stochastic"]]
    return _matrix


def case_by_name(name: str) -> dict | None:
    for case in matrix():
        if case["name"] == name:
            return case
    return None


def reference(name: str) -> list[int]:
    if name not in _refs:
        _refs[name] = M.read_wav(REFS / f"{name}.wav")
    return _refs[name]


def sweep(factory, only: list[str] | None = None) -> tuple[int, list[str]]:
    """Render every deterministic case with `factory` as the ring and
    byte-compare against the captured exports. Returns (n, failures)."""
    prev, M.make_history = M.make_history, factory
    cases = [c for c in matrix() if only is None or c["name"] in only]
    bad = []
    try:
        for case in cases:
            model = M.render_case(CASES / case["audio"],
                                  case["expected_ticks"])
            _, mism, _, _ = M.aligned_diff(model, reference(case["name"]),
                                           case["alignment_max_shift"])
            if mism:
                bad.append(f"{case['name']}({mism})")
    finally:
        M.make_history = prev
    return len(cases), bad


def sweep_report(name: str, factory, want_exact: bool, detail: str) -> None:
    n, bad = sweep(factory)
    ok = (not bad) if want_exact else bool(bad)
    got = (f"{n - len(bad)}/{n} byte-exact"
           + (f"; breaks {', '.join(bad[:4])}" if bad else ""))
    report(name, ok, f"{detail} - {got}")


# --- rendering one case under a chosen geometry ------------------------------

def render_witness_at(path: Path, ticks: int, factory):
    prev, M.make_history = M.make_history, factory
    try:
        return M.render_case(path, ticks)
    finally:
        M.make_history = prev


def observe(factory, images) -> dict[str, tuple[int, int]]:
    """Probe-recorded ranges while rendering `images` under a geometry."""
    ranges: dict[str, list[int]] = {}

    def rec(site, v):
        r = ranges.get(site)
        if r is None:
            ranges[site] = [v, v]
        elif v < r[0]:
            r[0] = v
        elif v > r[1]:
            r[1] = v

    prev_probe, M.probe = M.probe, rec
    prev, M.make_history = M.make_history, factory
    try:
        for path, ticks in images:
            M.render_case(path, ticks)
    finally:
        M.probe, M.make_history = prev_probe, prev
    return {k: (v[0], v[1]) for k, v in ranges.items()}


def bits_for(lo: int, hi: int) -> int:
    w = 1
    while lo < -(1 << (w - 1)) or hi > (1 << (w - 1)) - 1:
        w += 1
    return w


# --- layout: what the binary allocates, and what a replica must keep --------

def sec_layout() -> None:
    print("layout: the binary's per-voice storage, and the required subset")
    fields = [
        ("+0x0000", 0x2000, "int16 PCM work buffer (4,096 samples)",
         "not required - the replica streams samples, never buffers a block"),
        ("+0x2040", 366, "current 183-sample tick buffer",
         "not required as memory - one 16-bit sample register"),
        ("+0x21ae", 8 * 366, "eight-slot phaser/history ring",
         "REQUIRED - read back 366/732 samples later by the comb"),
        ("+0x2d30", 0x160, "oscillator and current-note state",
         "registers/state words, already in the RTL's slot records"),
    ]
    for off, size, what, verdict in fields:
        print(f"  {off:8s} {size:6,d} B  {what}")
        print(f"           {'':6s}     -> {verdict}")
    note("the record stride is 0x3700 B x 16 records = 220 KB; the RE notes' "
         "compatibility table already rules the 16-record array unobservable")

    # The two independent statements in the notes - the layout table's byte
    # count and the phaser section's "183 signed 16-bit samples per slot" -
    # agree on the entry width only at 16 bits. Same for the tick buffer.
    report("layout.entry_width_16",
           8 * TICK * 2 == 8 * 366 and TICK * 2 == 366,
           f"8 slots x {TICK} samples x 2 B = {8 * TICK * 2:,d} B = the "
           "recorded 8 x 366 B: entries are int16")
    note("so the comb's 17-bit feedback fixpoint (psg_hw_forms bound) is the "
         "ACCUMULATOR width, not the storage width - the binary stores the "
         "comb's result in an int16 cell and reads that cell back")


# --- entry: the storage width ------------------------------------------------

def sec_entry() -> None:
    print("entry: the ring cell's width")

    # The comb in its stored form. 4x + 2h = 2(2x + h), and tz halves that
    # exactly, so the hardware accumulator is 2x + h - one bit narrower
    # than the transcribed 4x + 2h.
    x_max, h_max = 26_880, 1 << 15
    a_max = 2 * x_max + h_max
    ok = all(M.tz(2 * a, 4) == M.tz(a, 2) for a in range(-a_max, a_max + 1))
    report("entry.comb_acc_narrower", ok,
           f"tz((4x+2h)/4) == tz((2x+h)/2) exhaustively over every "
           f"reachable accumulator value |2x+h| <= {a_max:,d} "
           f"({bits_for(-a_max, a_max)} bits, was "
           f"{bits_for(-2 * a_max, 2 * a_max)})")

    # A pre-halved cell would save a bit; it does not survive the rounding.
    bad = [(x, h) for x in range(-8, 9) for h in range(-8, 9)
           if M.tz(2 * x + h, 2) != x + M.tz(h, 2)]
    report("entry.lsb_load_bearing", bool(bad),
           f"storing tz(h/2) instead of h is NOT equivalent - "
           f"{len(bad)} counterexamples in |x|,|h| <= 8, first "
           f"x={bad[0][0]} h={bad[0][1]}: "
           f"{M.tz(2 * bad[0][0] + bad[0][1], 2)} vs "
           f"{bad[0][0] + M.tz(bad[0][1], 2)}; 16 bits is the floor")

    # What the content reaches BEFORE the cell truncates it, ordinary cases
    # and the deliberately-overflowing ladder reported apart.
    ladder = ["filter-reverb-fixpoint-sub", "filter-reverb-fixpoint-mid",
              "filter-reverb-fixpoint-full"]
    for label, group in (("ordinary",
                          [c for c in matrix() if c["name"] not in ladder]),
                         ("ladder",
                          [c for c in matrix() if c["name"] in ladder])):
        if not group:
            continue
        obs = observe(lambda: Ring(None),
                      [(CASES / c["audio"], c["expected_ticks"])
                       for c in group])
        lo, hi = obs["ring.entry"]
        measured(f"entry.range_{label}",
                 f"{len(group)} cases, pre-truncation ring values "
                 f"[{lo:,d}, {hi:,d}] = {bits_for(lo, hi)} bits"
                 + (" - the content the ordinary matrix reaches"
                    if label == "ordinary" else
                    " - past the cell on purpose"))

    # Two-sided: with the ladder in the matrix the width is pinned. Without
    # it the gate was blind on the narrow side, which is worth recording -
    # it is why the ladder had to be captured rather than reasoned about.
    passing = []
    for w in range(12, 21):
        _, bad_cases = sweep(lambda w=w: Ring(w, "wrap"))
        if not bad_cases:
            passing.append(w)
    report("entry.width_pinned", passing == [16],
           f"exactly one cell width renders all {len(matrix())} cases "
           f"byte-exact: {passing} - narrower loses the ordinary content, "
           "wider fails the ladder. The width is now a two-sided gate, not "
           "a layout inference")
    old = [c["name"] for c in matrix() if c["name"] not in ladder
           and not c["name"].startswith("filter-reverb-onset")
           and not c["name"].startswith("filter-reverb-level")
           and not c["name"].startswith("filter-reverb-pair")]
    blind = []
    for w in range(12, 21):
        _, bad_cases = sweep(lambda w=w: Ring(w, "wrap", ring_only=True),
                             only=old)
        if not bad_cases:
            blind.append(w)
    measured("entry.pre_capture_blindness",
             f"the {len(old)}-case matrix that existed before this capture "
             f"accepted cell widths {blind} - sizing the RAM from it would "
             "have shipped a cell too narrow for its own content, silent "
             "until a cart read back a loud voice")

    # The fixpoint ladder, captured from PICO-8 (2026-07-28). A DC wavetable
    # makes the tap reinforce at every lag, so the comb runs to y -> 2x and
    # the cell's overflow behaviour becomes audible. Three rungs: one under
    # int16, two over.
    ladder = ["filter-reverb-fixpoint-sub", "filter-reverb-fixpoint-mid",
              "filter-reverb-fixpoint-full"]
    hyps = [("int16 wrap", lambda: Ring(16, "wrap")),
            ("int16 saturate", lambda: Ring(16, "sat")),
            ("unbounded", lambda: Ring(None))]
    survivors = {label for label, _ in hyps}
    for name in ladder:
        case = case_by_name(name)
        if case is None or not (REFS / f"{name}.wav").exists():
            note(f"{name}: no capture installed - skipped")
            continue
        ref = M.read_wav(REFS / f"{name}.wav")
        obs = observe(lambda: Ring(None), [(CASES / case["audio"],
                                           case["expected_ticks"])])
        rlo, rhi = obs["ring.entry"]
        over = max(-rlo - (1 << 15), rhi - ((1 << 15) - 1))
        verdicts = []
        for label, factory in hyps:
            model = render_witness_at(CASES / case["audio"],
                                      case["expected_ticks"], factory)
            _, mism, _, _ = M.aligned_diff(model, ref,
                                           case["alignment_max_shift"])
            verdicts.append(f"{label} {'MATCH' if not mism else f'{mism:,d}x'}")
            if mism:
                survivors.discard(label)
        print(f"  {'LADDER':8s} {name:32s} "
              f"{'inside int16' if over <= 0 else f'over by {over:,d}':16s} "
              f"{'; '.join(verdicts)}")
    report("entry.cell_wraps", survivors == {"int16 wrap"},
           f"the only reading that matches every rung is {sorted(survivors)} "
           "- the cell is int16 and it WRAPS. Saturation and unbounded "
           "arithmetic are both refuted at the fixpoint, and the sub rung "
           "confirms the DC path itself is exact below it")
    note("so the RTL truncates to 16 bits and must NOT clamp - and the mix "
         "bus takes the wrapped value, since the binary's ring and tick "
         "buffer are the same int16 storage class. Wrapping is also the "
         "cheaper gate: no comparators")


# --- depth: the ring as a flat sample buffer --------------------------------

def sec_depth() -> None:
    print("depth: slots versus a flat sample buffer")

    # Which slot ages does the comb ever read? Writes advance rpos by one
    # per tick, so slot (rpos + k) & 7 was last written 8 - k ticks ago.
    ages = {lvl: set() for lvl in LOOKBACK}
    for rpos in range(8):
        for lvl in LOOKBACK:
            tap = (rpos + 4 + 2 * (lvl == 1)) & 7
            ages[lvl].add((rpos - tap) % 8)
    read = sorted(set().union(*ages.values()))
    never = [a for a in range(8) if a > max(read)]
    report("depth.dead_slots", read == [2, 4] and never == [5, 6, 7],
           f"reads land only at ages {read} ticks (levels "
           f"{ {k: sorted(v) for k, v in ages.items()} }); ages "
           f"{never} are written and NEVER read - {len(never)}/8 of the "
           "transcribed ring is dead")
    note(f"retention is therefore ages 0..{max(read)} = {max(read) + 1} "
         f"slots = {(max(read) + 1) * TICK:,d} samples; as a flat buffer the "
         f"requirement collapses to the lookback itself, "
         f"{LOOKBACK[2]:,d} samples")

    sweep_report("depth.flat_732_exact", lambda: FlatRing(LOOKBACK[2]),
                 True, f"flat {LOOKBACK[2]}-entry circular buffer replaces "
                       f"8 x {TICK} slots")
    sweep_report("depth.flat_731_breaks", lambda: FlatRing(LOOKBACK[2] - 1),
                 False, f"{LOOKBACK[2] - 1} entries")
    sweep_report("depth.flat_366_breaks", lambda: FlatRing(LOOKBACK[1]),
                 False, f"{LOOKBACK[1]} entries (level-1 lookback only)")
    n, bad = sweep(lambda: FlatRing(LOOKBACK[1]))
    note(f"the {LOOKBACK[1]}-entry buffer breaks exactly the level-2 cases "
         f"({', '.join(b.split('(')[0] for b in bad)}) and nothing else, so "
         f"a build restricted to reverb level 1 is exact at half the depth")
    note(f"at exactly {LOOKBACK[2]} entries the level-2 read address equals "
         f"the write address (n-732 == n mod 732), so the RTL must read "
         f"before write on that port; {LOOKBACK[2] + 1} entries removes the "
         "collision, and block quantization gives 768 anyway (see fit)")
    saved = 8 * TICK - LOOKBACK[2]
    report("depth.halves_the_ring", saved == LOOKBACK[2],
           f"{8 * TICK:,d} -> {LOOKBACK[2]:,d} entries per voice: exactly "
           f"2x, {saved:,d} entries of pure waste retired")


# --- count: how many rings ---------------------------------------------------

def sec_count() -> None:
    print("count: how many rings a replica needs")
    note("RE notes, normal-mode callback rule: 16 records render, but "
         "classic PSG playback uses 8 - a foreground and a music state per "
         "logical channel; slots 8..15 serve the generic sound player")
    note("'the hidden music state continues to advance while replaced' and "
         "rendering advances 'oscillator phase, SFX row/effect position, "
         "PHASER HISTORY' - a muted music voice keeps filling its ring, and "
         "reads it back when the foreground SFX ends, so audibility does "
         "NOT bound the ring count")
    note("the four-audible invariant (psg_hw_forms bound.mix_never_clips) "
         "bounds the mix bus, not storage: 8 concurrently advancing states "
         "means 8 rings for unconditional exactness")

    # Captured 2026-07-28: filter-reverb-onset settles it. A reverb-FREE
    # SFX runs first, then a reverb-2 SFX launches on the same voice; the
    # export's echo is there from the switch, so the ring was being filled
    # all along.
    sweep_report("count.write_is_unconditional", LazyRing, False,
                 "writing only while the comb is enabled")
    onset = case_by_name("filter-reverb-onset")
    if onset and (REFS / "filter-reverb-onset.wav").exists():
        ref = M.read_wav(REFS / "filter-reverb-onset.wav")
        img, ticks = CASES / onset["audio"], onset["expected_ticks"]
        for label, factory in (("always (the binary)", M.SlotRing),
                               ("only while armed (a pool)", LazyRing)):
            model = render_witness_at(img, ticks, factory)
            _, mism, _, first = M.aligned_diff(model, ref,
                                               onset["alignment_max_shift"])
            print(f"  {'ONSET':8s} {label:26s} "
                  f"{'BYTE-EXACT' if not mism else f'{mism:,d} differ'}")
        report("count.eight_rings_needed", True,
               "a voice fills its ring whether or not its own comb is "
               "reading it, so a slot that later carries reverb hears "
               "history from before it armed - all 8 concurrently advancing "
               "states need storage for unconditional exactness")
    note("a K-ring pool is therefore a deliberate approximation, not a "
         "second reading of the binary. levers prices its error")


# --- corpus: what the shipped carts ask for ---------------------------------

def sec_corpus() -> None:
    print("corpus: filters in the shipped cart audio")
    for name in ("celeste_audio.bin", "nemo_audio.bin"):
        p = Path("build") / name
        if not p.exists():
            note(f"{p} absent (make psg-wav CART=... builds it) - skipped")
            continue
        blob = p.read_bytes()
        used = rev = damp = det = other = 0
        for s in range(64):
            sfx = M.Sfx(blob[256 + 68 * s:256 + 68 * (s + 1)])
            if any(n["vol"] for n in sfx.notes):
                used += 1
            rev += sfx.reverb > 0
            damp += sfx.dampen > 0
            det += sfx.detune > 0
            other += sfx.noiz or sfx.buzz
        worst = 0
        for pat in range(64):
            live = [blob[4 * pat + c] for c in range(4)]
            worst = max(worst, sum(
                1 for b in live if not b & 0x40
                and M.Sfx(blob[256 + 68 * (b & 0x3F):
                               256 + 68 * ((b & 0x3F) + 1)]).reverb))
        measured(f"corpus.{name.split('_')[0]}",
                 f"{used} sounding SFX; reverb {rev}, dampen {damp}, "
                 f"detune {det}, noiz/buzz {other}; max simultaneous "
                 f"reverb channels over all 64 patterns: {worst}")
    note("the shipped corpus enables no filter at all, so REVERB=0 on the "
         "iCE40 target costs zero fidelity on the content that ships - the "
         "ring buys capability for other carts, not parity for ours")


# --- fit: block-quantized cost ----------------------------------------------

CANDIDATES = [
    (f"transcribed 8x{TICK} slots x 17b", 8 * TICK, 17, 1),
    (f"transcribed 8x{TICK} slots x 16b", 8 * TICK, 16, 1),
    ("flat 732 x 17b", LOOKBACK[2], 17, 1),
    ("flat 732 x 16b   <- MINIMAL EXACT", LOOKBACK[2], 16, 1),
    ("flat 733 x 16b (no r/w collision)", LOOKBACK[2] + 1, 16, 1),
    ("flat 366 x 16b (level-1 only)", LOOKBACK[1], 16, 1),
    ("minimal x 4 voices", LOOKBACK[2], 16, 4),
    ("minimal x 8 voices", LOOKBACK[2], 16, 8),
]


def rtl_fingerprint() -> str:
    """The Makefile's fingerprint: a block count without one is not
    reproducible across RTL revisions (docs/build-targets.md)."""
    import hashlib
    h = hashlib.sha1()
    for p in sorted(Path("rtl").glob("*.sv")) + sorted(Path("rtl").glob("*.v")):
        h.update(p.read_bytes())
    return h.hexdigest()[:12]


def ebr_census() -> tuple[dict[str, int], str] | None:
    """The measured per-array EBR census of target_psg, from the netlist
    yosys already produced (make synth-psg), with a stamp saying which
    netlist it was. A half-written JSON reads as absent rather than as a
    smaller design."""
    p = Path("build/targets/psg.json")
    if not p.exists():
        return None
    try:
        net = json.loads(p.read_text())
    except json.JSONDecodeError:
        return None
    out: dict[str, int] = {}
    for mod in net["modules"].values():
        for name, cell in mod.get("cells", {}).items():
            if "RAM40" in cell["type"]:
                arr = name.split(".")
                key = arr[-3] if len(arr) >= 3 else name
                out[key] = out.get(key, 0) + 1
    import datetime
    stamp = datetime.datetime.fromtimestamp(
        p.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
    return out, f"netlist {stamp}, rtl/ now at {rtl_fingerprint()}"


def sec_fit() -> None:
    print("fit: block cost of every candidate geometry, per target")
    print(f"  {'geometry':36s} {'bits':>8s} {'iCE40':>7s} {'aspect':>7s} "
          f"{'Gowin':>6s}")
    for label, depth, width, n in CANDIDATES:
        b = depth * width * n
        ni = n * blocks(depth, width, ICE40)
        na, ra = aspect(depth, width, ICE40)
        ng = n * blocks(depth, width, GOWIN)
        print(f"  {label:36s} {b:8,d} {ni:7d} {n * na:3d} @{ra[0]}x{ra[1]:<2d}"
              f" {ng:6d}")
    note("the iCE40 column is the bit floor (yosys lane-packs to it, "
         "measured by the synth section); the aspect column is what a single "
         "aspect ratio would cost. The floor is why the 16-bit cell wins: "
         f"{blocks(LOOKBACK[2], 16, ICE40)} blocks against "
         f"{blocks(LOOKBACK[2], 17, ICE40)} for 17 bits, and "
         f"{blocks(8 * TICK, 17, ICE40)} for the transcribed ring - the "
         "minimal geometry is 2.3x cheaper than the literal reading of the "
         "binary")

    print()
    got = ebr_census()
    if got is None:
        note("build/targets/psg.json absent or being rewritten "
             "(make synth-psg) - skipping the measured census")
        return
    census, stamp = got
    print(f"  measured EBR census, target_psg (REVERB=1; {stamp}):")
    for name, n in sorted(census.items(), key=lambda kv: -kv[1]):
        print(f"    {name:16s} {n:2d}")
    total = sum(census.values())
    freed = census.get("wrom", 0) + census.get("revbuf", 0)
    base = total - freed
    ceiling = 15
    ring = blocks(LOOKBACK[2], 16, ICE40)
    print(f"    {'total':16s} {total:2d}  (the {ceiling}-block ceiling "
          "recorded in reduce-psg-ice40-area: the PPU already owns sixteen "
          "of the HX8K's 32)")
    note(f"adoption retires wrom (waves compute) and the shared post-mix "
         f"revbuf (design 7 relocates the filters): {freed} blocks back, "
         f"{base} committed")
    note("aram's 9 blocks are not reducible: it is CPU-visible memory behind "
         "$00/$01/$02 that must read back what the cart wrote, byte for byte, "
         "whether or not the synthesizer reads every bit (the filter byte's "
         "bit 0 never reaches the pipeline, and no digit combination uses the "
         "top of the byte - dead bits in a store that still has to keep them)")
    for rings in (0, 1, 2, 4, 8):
        cost = base + rings * ring
        verdict = ("fits" if cost <= ceiling else
                   "over budget" if cost <= 32 else "over the HX8K device")
        exact = {0: "no reverb at all (today's iCE40 build)",
                 1: "byte-exact while at most ONE voice carries reverb",
                 2: "two concurrent reverb voices",
                 4: "the four music slots",
                 8: "unconditional: all 8 advancing states"}[rings]
        print(f"    {rings} ring(s): {cost:2d} blocks - {verdict:20s} {exact}")
    note(f"the headline: ONE exact ring costs {base + ring} blocks - the same "
         f"{ceiling} the shipping build already spends - and it REPLACES the "
         "10-bit shared post-mix approximation. Exactness for a single "
         "reverb-carrying voice is free on iCE40; the second voice is not")
    g_tables = (blocks(4608, 8, GOWIN) + blocks(256, 16, GOWIN)
                + blocks(256, 16, GOWIN) + blocks(8 * 32, 16, GOWIN))
    g_rings = 8 * blocks(LOOKBACK[2], 16, GOWIN)
    print(f"  Gowin GW2AR-18C (46 BSRAM, floor estimate - that flow is "
          f"separate): aram+crom+recip+state_m ~{g_tables}, 8 exact rings "
          f"{g_rings} = {g_tables + g_rings} of 46. Unconditional exactness "
          "fits the Tang Nano 20K, which is the board the console actually "
          "ships on (docs/build-targets.md: the soc does not place on the "
          "HX8K at all)")


# --- synth: measure the floor claim -----------------------------------------

def sec_synth() -> None:
    print("synth: measured iCE40 block cost per geometry (needs yosys)")
    import shutil
    import subprocess
    if not shutil.which("yosys"):
        note("yosys not on PATH - skipped")
        return
    SCRATCH.mkdir(parents=True, exist_ok=True)
    src = SCRATCH / "geometry.sv"
    for label, depth, width, n in CANDIDATES:
        arrays = "".join(f"  logic signed [{width - 1}:0] m{i}[0:{depth - 1}];"
                         f"\n  logic signed [{width - 1}:0] q{i};\n"
                         for i in range(n))
        body = "".join(f"    q{i} <= m{i}[ra % {depth}];\n"
                       f"    if (we[{i}]) m{i}[wa % {depth}] <= din;\n"
                       for i in range(n))
        src.write_text(
            f"module geometry(input clk, input [15:0] wa, ra,\n"
            f"    input signed [{width - 1}:0] din, input [{n - 1}:0] we,\n"
            f"    output signed [{width - 1}:0] dout);\n{arrays}"
            f"  always_ff @(posedge clk) begin\n{body}  end\n"
            f"  assign dout = {' ^ '.join(f'q{i}' for i in range(n))};\n"
            f"endmodule\n")
        out = subprocess.run(
            ["yosys", "-p", f"read_verilog -sv {src}; "
             "synth_ice40 -top geometry -json /dev/null"],
            capture_output=True, text=True).stdout
        ebr = [int(m) for m in re.findall(r"^\s+(\d+)\s+SB_RAM40_4K$",
                                         out, re.M)]
        lut = [int(m) for m in re.findall(r"^\s+(\d+)\s+SB_LUT4$", out, re.M)]
        want = n * blocks(depth, width, ICE40)
        got = ebr[-1] if ebr else 0
        report(f"synth.{depth}x{width}x{n}", got <= want,
               f"{label}: {got} EBR (floor {want}), "
               f"{lut[-1] if lut else 0} LUT4 for the lane muxing")


# --- levers: what else can be freed, and what each unlocks -----------------

def sec_levers() -> None:
    print("levers: what else is available, and what each one unlocks")
    got = ebr_census()
    if got is None:
        note("build/targets/psg.json absent or being rewritten "
             "(make synth-psg) - skipped")
        return
    census, stamp = got
    note(f"block counts below are from the {stamp} - re-measure after RTL changes")
    ring = blocks(LOOKBACK[2], 16, ICE40)
    ceiling = 15
    base = sum(census.values()) - census.get("wrom", 0) \
        - census.get("revbuf", 0)

    # 1. recip: a rounded reciprocal the adoption retires anyway.
    bad = tot = worst = 0
    for d in range(1, 256):
        r = min(0xFFFF, round(65536 / d))
        for t in range(d):
            tot += 1
            if (r * t) >> 8 != (t * 256) // d:
                bad += 1
                worst = max(worst, abs(((r * t) >> 8) - (t * 256) // d))
    num = 255 * (63 << 16)
    report("levers.recip_is_approximate", bad > 0,
           f"recip[s] = round(65536/s) with a >>8 product differs from exact "
           f"truncated division on {bad:,d}/{tot:,d} (t,d) pairs (max {worst} "
           "of 256) - the adoption retires the form, so its EBR is in play")
    note(f"the replacement is exact `tz(N, d)`: N <= {num:,d} "
         f"({num.bit_length()} bits) over d <= 255, three divides per "
         f"voice-tick. A restoring divide is {num.bit_length()} cycles on "
         f"the existing serial adder: {3 * num.bit_length() * 8:,d} clocks "
         f"per tick against {TICK * 1275:,d} available - 0.3%. Trading "
         f"{census.get('recip', 0)} EBR for adder cycles on the BINDING "
         "resource is the same trade the hybrid wave ROM already took")

    # 2. aram: three quarters of the budget, and bandwidth-trivial to move.
    per_tick = 8 * (2 + 4 + 2 + 64)
    note(f"aram is {census.get('aram', 0)} of {sum(census.values())} blocks - "
         f"the only lever that changes a TIER. It is a copy of cart memory "
         f"the CPU already holds; PICO-8 itself reads the live image. Worst "
         f"case traffic is {per_tick} B/tick (8 voices x note+header+"
         f"instrument row+64-byte wavetable) = {per_tick * 12049 // 100:,d} "
         "B/s, ~2% of a 1 B/clk main memory. Bandwidth is not the obstacle; "
         "the register map is, and it is a stated non-goal here "
         "(add-memory-subsystem owns it)")

    print()
    print("  tier ladder (iCE40, 15-block ceiling):")
    ladder = [
        ("today: approximate shared reverb", sum(census.values()), 0),
        ("adoption only (wrom + revbuf out)", base, 0),
        ("  + 1 exact ring", base, 1),
        ("  + recip retired, 1 ring", base - census.get("recip", 0), 1),
        ("  + recip retired, 2 rings", base - census.get("recip", 0), 2),
        ("  + aram relocated, 4 rings",
         base - census.get("recip", 0) - census.get("aram", 0), 4),
        ("  + aram relocated, 8 rings",
         base - census.get("recip", 0) - census.get("aram", 0), 8),
    ]
    for label, tables, rings in ladder:
        cost = tables + rings * ring
        print(f"    {label:36s} {cost:2d} blocks  "
              f"{'fits' if cost <= ceiling else 'OVER'}")
    note("so exactness for one reverb-carrying voice is available now; the "
         "four music slots need aram out of EBR; eight need that AND more "
         "budget than the PSG's share of the HX8K. The Tang Nano needs none "
         "of this - it is 8 BSRAM of 46 there")

    # 3. The pool's error against the CAPTURED reference (count refuted the
    #    pool as a reading of the binary; this is what choosing it costs).
    onset = case_by_name("filter-reverb-onset")
    if onset is None or not (REFS / "filter-reverb-onset.wav").exists():
        note("filter-reverb-onset not captured - pool cost unpriced")
        return
    p, ticks = CASES / onset["audio"], onset["expected_ticks"]
    full = render_witness_at(p, ticks, M.SlotRing)
    pool = render_witness_at(p, ticks, LazyRing)
    diff = [i for i in range(len(full)) if full[i] != pool[i]]
    if not diff:
        report("levers.pool_exposure", False,
               "the onset case does not separate the two readings")
        return
    first = diff[0]
    laps = []
    for k in range(4):
        lo = first + k * LOOKBACK[2]
        hi = lo + LOOKBACK[2]
        window = [abs(full[i] - pool[i]) for i in diff if lo <= i < hi]
        laps.append(max(window) if window else 0)
    measured("levers.pool_exposure",
             f"against the captured filter-reverb-onset, allocating the ring "
             f"at arm time instead of writing it always diverges from sample "
             f"{first} (tick {first // TICK}, the reverb SFX's first), peak "
             f"per 732-sample lap {laps} counts - the missing echo, halving "
             "every lap rather than a permanent offset")
    note("so a pool is a priced approximation: exact except for a decaying "
         "window after a reverb digit arrives on a slot that had none. "
         "Sticky per-slot ownership removes even that for any cart that "
         "keeps reverb on one voice - which is every cart in the corpus")


# --- borrow: storage strategies from other sound chips, priced here --------

def sec_borrow() -> None:
    print("borrow: what other sound chips do about storage, priced for this "
          "fabric")
    note("Paula (Amiga, nonarkitten/amiga_replacement_project/paula/Paula.v): "
         "four channels time-multiplexed through ONE datapath - 'Audio state "
         "machines HW are time-multiplexed to save resource' - and it owns "
         "NO sample memory. Its largest audio array is 4 x 16 bits; the "
         "whole audio side is "
         f"{4 * (16 + 16 + 7 + 16 + 7 + 16 + 8 + 3 + 9)} bits of per-channel "
         "registers. Samples arrive by DMA from chip RAM through a two-stage "
         "buffer (AUDxDAT -> audbuf -> smpbuf) so bus jitter never reaches "
         "the sample clock. GPL v3: the idea travels, the code does not")
    note("S-DSP (SNES) is the same move for the part we care about: its echo "
         "delay line lives in APU RAM at a programmable base (ESA) with a "
         "programmable length (EDL), not in the chip. That is exactly our "
         "reverb ring - the one structure we cannot compress and cannot fit")

    # What relocation would cost in traffic. The ring is 1 tap read + 1 write
    # per sample per voice, plus the crossfade's second tap on the 64
    # continuation samples when the old state's level differs (sixth
    # milestone). Bytes are 2 per access at the proven 16-bit cell.
    per_voice_tick = TICK + BLEND + TICK
    voices = 8
    per_tick = voices * per_voice_tick * 2
    per_sec = per_tick * 12049 // 100
    acc_per_sample = voices * per_voice_tick / TICK
    report("borrow.ring_traffic_is_small", acc_per_sample < 1275 / 10,
           f"relocating all 8 rings costs {per_voice_tick} accesses per "
           f"voice-tick ({TICK} tap + {BLEND} continuation tap + {TICK} "
           f"write) = {acc_per_sample:.1f} accesses per sample, "
           f"{per_sec:,d} B/s worst case - {acc_per_sample / 1275:.1%} of "
           "the PSG's own 1,275-clock sample budget. The PSG side is free; "
           "the shared bus is the only question")
    note("and it is zero for the shipped corpus: no cart in it enables a "
         "reverb digit, so the ring is never read and never written")
    note("relocation is fidelity-NEUTRAL by construction - depth.flat_732 "
         "already proves the model cannot tell one 732-entry buffer from "
         "another, only its depth and cell. Every other lever trades "
         "fidelity or area; this one trades storage for bandwidth")

    # The obvious alternative, refuted with the device's own numbers.
    ffs = LOOKBACK[2] * 16
    report("borrow.shift_register_refuted", ffs > 7680,
           f"the JT12/OPN trick - rotate per-voice state through a shift "
           f"register instead of an addressed RAM, which suits a fabric with "
           f"LUT shift registers - needs {ffs:,d} flip-flops for ONE ring "
           f"against the HX8K's 7,680 logic cells ({ffs / 7680:.1f}x the "
           "whole device). iCE40 has no LUT-RAM or SRL primitive; the EBR is "
           "the only dense store on this part")
    note("Paula's volume-by-PWM (a 6-bit counter compared against the volume "
         "register, no multiplier at all) and its channel-per-delta-sigma "
         "output with no digital sum are both refused here for the same "
         "reason: our gate is byte-exactness against tz(G*z/3072) and the "
         "nonlinear soft_add tree, so the mix must be formed digitally and "
         "exactly. The no-multiplier GOAL is already met by other means - "
         "psg_hw_forms proves every product as CSD adder networks or serial "
         "service passes, because this fabric has no DSP either")
    note("what Paula confirms rather than teaches: one datapath shared "
         "across voices (our m-service and visit schedule already do this) "
         "and a delta-sigma output stage (rtl/dsigma.sv). The genuinely new "
         "idea is the double buffer - a fetched word and an in-use word per "
         "voice - which is what makes a shared-bus fetch safe when the "
         "sample clock cannot wait")

    got = ebr_census()
    if got is None:
        return
    census, stamp = got
    ring = blocks(LOOKBACK[2], 16, ICE40)
    base = sum(census.values()) - census.get("wrom", 0) \
        - census.get("revbuf", 0)
    print()
    print("  what the two relocations do to the tier ladder:")
    for label, tables, rings in (
            ("EBR-resident (today's plan)", base, 1),
            ("ring in main RAM", base, 0),
            ("aram in main RAM", base - census.get("aram", 0), 1),
            ("both, all 8 rings exact",
             base - census.get("aram", 0), 0)):
        cost = tables + rings * ring
        print(f"    {label:32s} {cost:2d} blocks  "
              f"{'fits' if cost <= 15 else 'OVER'}")
    note("the bottom row is the Paula/S-DSP architecture: the audio chip "
         "keeps registers and tables, the CART IMAGE and the DELAY LINE live "
         "in the memory the CPU already has, and unconditional eight-ring "
         "exactness lands on iCE40 with blocks to spare. It needs the "
         "register map to change and a reserved bus slot to exist - both "
         "owned by add-memory-subsystem, both stated non-goals here")
    note("the one hard requirement it inherits from Paula: a GUARANTEED "
         "slot. Paula steals a fixed DMA slot per channel per scanline, so "
         "its fetch can never be late. Our gate is byte-exactness, where a "
         "late fetch is a WRONG sample rather than a glitch - so the "
         "subsystem must reserve the bandwidth, not merely usually have it")


SECTIONS = {"layout": sec_layout, "entry": sec_entry, "depth": sec_depth,
            "count": sec_count, "corpus": sec_corpus, "levers": sec_levers,
            "borrow": sec_borrow, "fit": sec_fit, "synth": sec_synth}


def main() -> int:
    global CASES, REFS
    ap = argparse.ArgumentParser()
    ap.add_argument("sections", nargs="*", default=[])
    ap.add_argument("--cases", type=Path, default=CASES)
    ap.add_argument("--reference", dest="refs", type=Path, default=REFS)
    args = ap.parse_args()
    CASES, REFS = args.cases, args.refs

    for name in (args.sections or list(SECTIONS)):
        SECTIONS[name]()
        print()
    if FAILURES:
        print(f"REFUTED: {', '.join(FAILURES)}")
        return 1
    print("every geometry claim holds on its stated domain")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
